### ISSUE TITLE
[question] Windows capture upscaling.

### ISSUE THREAD

**Issue by CortexReaver** [ryandash/Anime4k-obs-upscaling-shaders#2]
Will these shaders work with "window capture" and not a "video capture device"? I want to upscale old RPG maker VX games to make it look good on my stream.
Or I have to use all sorts of virtual cameras shenanigans in order to make it work just with windowed games?

**Comment by ryandash** [comment]
I have not tested my shaders with anything besides a video capture card source but in theory these shaders can work as long as source mirrors can be made of the original source. Please be aware that newer versions of OBS might have issues involving streamfx. I do not have access to the newer versions of streamfx to test with them.

**Comment by CortexReaver** [comment]
Ok, thanks for answer. I think this one here is the latest one: https://github.com/xoxfaby/obs-StreamFX It's pretty much the same thing, just compiled binaries of the original github repository.

**Comment by ryandash** [comment]
As far as i am aware, the developer of the streamfx plugin has stopped releasing any new changes to the public and requires a patreon subscription to get new builds. Examining their patreon, the latest build they made was StreamFX v1.0.0 Beta 473 on the 2nd of February. https://www.patreon.com/Xaymar

I do not personally have access to those builds to test but I do know that my shaders did work on previous versions and were broken at some point before the developer decided to go patreon only. Newer builds may have fixed the issues if you are willing to pay for them. I have tried previously to get my shaders working with the last public release but failed. Other example shaders provided by streamfx such as smaa use a simular approach to what I am doing and those also seem to fail which does not sound promising.
