### ISSUE TITLE
[Crash] OBS crashes when I try to select a source in "Shader Parameters" w\ streamFX

### ISSUE THREAD

**Issue by CortexReaver** [ryandash/Anime4k-obs-upscaling-shaders#3]
OBS version 30.1.0-beta1, streamFX version 0.12.0b299 (I cannot get the binaries for any other version anywhere and OBS 27 doesn't work with this version of stream fx)

here's the log: [LOG.txt](https://github.com/ryandash/Anime4k-obs-upscaling-shaders/files/14232150/LOG.txt)

I've also tried to use the other plugin for shaders: https://github.com/exeldro/obs-shaderfilter and this one for "source mirroring": https://obsproject.com/forum/resources/source-clone.1632/
And this is doesn't work as well. I mean its not crashing, but there is a lot of other options in your shader and I don't know what to chose:

![11-02-2024 143143](https://github.com/ryandash/Anime4k-obs-upscaling-shaders/assets/34350690/d087a4ca-0c24-4818-ac51-22be261b9705)

**Comment by ryandash** [comment]
Currently the only plugin I can verify that worked was streamfx 0.11.1 which is no longer available to download as a binary through the official github. Most of the parameters that you are seeing should not be modifiable by the user which probably means that the other plugin is setup differently from streamfx. I will take a look at the other plugin and see if I can get my shaders working with it when I have time.

**Comment by ryandash** [comment]
I updated the shaders to work with source-clone and obs-shaderfilter. Please tell me if there are any issues.

**Comment by CortexReaver** [comment]
There are some problems, I've created a new issue for this.
